/**
 * @file ml_config_defaults.h
 * @brief Kconfig replacement defaults for non-IDF (Arduino/PlatformIO) builds.
 *
 * Upstream MicroLink gets all CONFIG_ML_* symbols from sdkconfig.h
 * (generated by Kconfig). Arduino-ESP32 ships a prebuilt sdkconfig.h
 * that defines none of them, so this header provides #ifndef-guarded
 * defaults. It is included by microlink_internal.h immediately AFTER
 * sdkconfig.h, so real sdkconfig values (or -D overrides) always win.
 *
 * Values below are tuned for ESP32-C3 (single-core, no PSRAM, ~380KB RAM).
 *
 * Feature-enable symbols (CONFIG_ML_ENABLE_CELLULAR,
 * CONFIG_ML_ENABLE_NET_SWITCH, CONFIG_ML_ENABLE_CONFIG_HTTPD,
 * CONFIG_ML_ZERO_COPY_WG) are intentionally NOT defined here:
 * absent means disabled via the existing #ifdef guards.
 */

#pragma once

/* Maximum simultaneous WireGuard/DISCO peers.
 * MUST match WIREGUARD_MAX_PEERS in WireGuardLwip/src/wireguard-platform.h.
 * Override only via a global -D visible to BOTH libraries. */
#ifndef CONFIG_ML_MAX_PEERS
#define CONFIG_ML_MAX_PEERS 4
#endif

/* Peers cached in NVS across reboots (ml_peer_nvs.c has its own
 * fallback of 64; this makes the C3-tuned value explicit). */
#ifndef CONFIG_ML_NVS_MAX_PEERS
#define CONFIG_ML_NVS_MAX_PEERS 16
#endif

/* HTTP/2 receive buffer for control-plane MapResponse (KB). */
#ifndef CONFIG_ML_H2_BUFFER_SIZE_KB
#define CONFIG_ML_H2_BUFFER_SIZE_KB 16
#endif

/* JSON parse buffer for control-plane responses (KB). */
#ifndef CONFIG_ML_JSON_BUFFER_SIZE_KB
#define CONFIG_ML_JSON_BUFFER_SIZE_KB 16
#endif

/* Optional priority peer VPN IP as a dotted-quad string literal
 * (used with strlen()/microlink_parse_ip() in microlink.c).
 * Empty string = none. */
#ifndef CONFIG_ML_PRIORITY_PEER_IP
#define CONFIG_ML_PRIORITY_PEER_IP ""
#endif

/* Device hostname prefix string literal. Empty = "esp32" fallback. */
#ifndef CONFIG_ML_DEVICE_NAME
#define CONFIG_ML_DEVICE_NAME "crosspoint"
#endif
